export BCM_LCD_INCLUDE := $(kbuild-dir)/include

obj-y += bmem_wrapper/
#obj-y += dss/
#obj-y += displays/
#obj-y += fb/
obj-$(CONFIG_FB_BCM_215XX) += dss/
obj-$(CONFIG_FB_BCM_215XX) += displays/
obj-$(CONFIG_FB_BCM_215XX) += fb/
obj-$(CONFIG_FB_BRCM_DSI) += dsi/
obj-y += hantro/memalloc_wrapper/
obj-y += ge/gememalloc_wrapper/
